### ISSUE TITLE
[HELP] - Helper Auto Index timing out

### ISSUE THREAD

**Issue by twinkie0101** [Aerilym/photoprism-helper#13]
**Describe the issue**
I've got auto index set up in docker (via Unraid).  Only option I planned on using.  The task is scheduled and run but I get a timeout error every time.

```
[2022-12-11 17:21:20] info: Timezone set to America/New_York
[2022-12-11 17:21:20] info: Targeting PhotoPrism instance at http://192.XXX.XX.XX:2342/
[2022-12-11 17:21:20] info: Scheduling auto index task.
[2022-12-11 17:21:20] info: PhotoPrism Helper API listening on port 2343
[2022-12-12 08:00:00] info: Running auto index.
[2022-12-12 08:00:31] error: timeout of 30000ms exceeded
[2022-12-12 08:00:31] info: Unknown error
```

**To Reproduce**

Not sure how to reproduce.  Included docker settings below.  The one thing I was unsure of on the setup is how to handle the API.  I generated an API for the container, but if there is something I need to do in PhotoPrism, not sure what that is.  Acknowledging my API understanding is limited.

**Expected behavior**

Run auto index every day.

**Screenshots**

![image](https://user-images.githubusercontent.com/79336898/207135827-af6fab6c-2403-428e-abb9-5dcff31e5fb1.png)
![image](https://user-images.githubusercontent.com/79336898/207135930-8f8a4c3a-c27b-46f0-bfc2-2348fcb03f1c.png)

**Additional context**
None.

**Comment by Aerilym** [comment]
Hi, so just to clarify a few things:
- You don't need to worry about the API key or the API stuff, as that's just used if you want to send API calls to the helper (not to PhotoPrism). The helper uses your given PhotoPrism username and password to make requests to PhotoPrism.
- The timeout message can be misleading as it's just waiting to receive a success message from PhotoPrism, so if the task takes longer than the timeout time, the helper will "timeout" and let you know.

I would recommend extending the timeout to a larger number, making it `3600000` would have it wait for 1 hour for a response. This should be enough time. If PhotoPrism has a lot of files to index, it can take a long time and might still fail. If this fails, please get back to me. Another thing to check is to see if it is actually indexing when it starts. Keep an eye on your PhotoPrism logs when its supposed to start, for me they're located at `http://192.168.1.113:2342/library/logs` (change it to your PhotoPrism location)

### Adding the index timeout variable
In the settings, if you don't already have an index timeout field:
1. Click the add variable button at the bottom
![image](https://user-images.githubusercontent.com/5667907/208223089-14dfba7b-b7e3-4600-bfa5-49ae85cd3afc.png)

2. Use the following settings:
![image](https://user-images.githubusercontent.com/5667907/208223036-b1b1b723-c5e0-4253-9053-30ad78c00e6d.png)

**Comment by twinkie0101** [comment]
Thanks, it's working as expected. Appreciate your work here!
